### ISSUE TITLE
Add submit button in this Quiz application.

### ISSUE THREAD

**Issue by pratikbug24** [pratikbug24/quiz-application#1]

**Comment by StefanG1102** [comment]
hey @pratikbug24 where would you like to have the Submit Button and what should it do? I would like to help you with that.

**Comment by pratikbug24** [comment]
The submit function is not call in program

**Comment by pratikbug24** [comment]
You are clone this repository and see the output and then see the submit button is not shown in front end.

**Comment by StefanG1102** [comment]
I would like to programm it for you can you assign me to the issue? 
Should i do something else ?
